AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  decompressor
  SAM Template for decompressor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  DecompressorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: decompressor_function/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      MemorySize: 10240
      EphemeralStorage:
        Size: 10240
      Environment:
        Variables:
          LOG_LEVEL: INFO
          TARGET_BUCKET_NAME: your-target-bucket-name-here
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DecompressorFunction:
    Description: "Decompressor Lambda Function ARN"
    Value: !GetAtt DecompressorFunction.Arn
  DecompressorFunctionIamRole:
    Description: "Implicit IAM Role created for Decompressor function"
    Value: !GetAtt DecompressorFunctionRole.Arn
